"use client";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { Toaster } from "@/components/ui/sonner";
import { usePathname } from "next/navigation";
import { UpdateCartContext } from "./_context/UpdateCartContext";
import { useEffect, useState } from "react";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";
import { getCartItemsApi } from "./_utils/GlobalApi";

const outfit = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params = usePathname();
  const [updateCart, setUpdateCart] = useState(false);
  const [loading, setLoading] = useState(false);
  const [cartItemsList, setCartItemsList] = useState();

  useEffect(() => {
    getCartItems();
  }, [updateCart]);

  const jwt = localStorage.getItem("jwt");
  const user = JSON.parse(localStorage.getItem("user"));
  const showHeader =
    params == "/sign-in" || params == "/create-account" ? false : true;
  const getCartItems = async () => {
    try {
      const cartItemsList = await getCartItemsApi(user.id, jwt);
      setCartItemsList(cartItemsList);
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <PayPalScriptProvider
      options={{ clientId: process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID }}>
      <html lang="en">
        <UpdateCartContext.Provider
          value={{ updateCart, setUpdateCart, loading, setLoading  ,cartItemsList,setCartItemsList}}>
          <body className={outfit.className}>
            {showHeader && <Header />}
            {children}
            <Toaster />
          </body>
        </UpdateCartContext.Provider>
      </html>
    </PayPalScriptProvider>
  );
}
